language: node_js
node_js:
- 6.9.2
deploy:
  - provider: npm
    email: david.beale@bealearts.co.uk
    api_key:
      secure: MsIxauc8Aw8QmJ6tnE4D2okY/dwiE822ezvtJf3eDJf0vjfUo+y7rn+5am8v/xEl/zDLInBm9IwBobjdKarK6l7ptjtf9S99RwiEwa2oYnrOa39yZ9eVY/Gn5KtGcNuI13Yb0uJ0kEPGiK9l0Q9CGKpVF1LfmFDCslr0Xa8JFaZz6ypP+MIA1K30JKFtVaxIhOvo+1DCbIO9ZFHXoefolfE2ZhsGX53TQG4A5Twjs1x24wcVxnkzrHzLYuCGTcpVv4tnJuckq6sp1p4CaBTEVaolJYslZWU0Ewc1U/ClW5CKpuxpjiJqT4tQmjNpLQTPu+SqmuG0QoN7Fy72k4ZHmhHlsb2yUrBSf4Zt0AlE4CIYrhxlush0nB6OWG9dHuExuo15i6ALBmehNz0tVWLpMGfDkKB3pnicyTRjVrerZFl+O5vR9BJqqz9wVOx2mEq5POljlTIoBrJaAYCxnjg0O9HbWK2Tdb2jayCOAng18g9ii9I7X2ewAddOTCg/uYgBU0iQXtq95a+CBiEEZ11Jd9CHTETIXmfWgorBC31ZnqXeTfdgIGQVrbG/YMMBeop8IdS9+L98BAmKyX8WPEnTotsh3i3ZqSHf6geBzGSb8rtCRexq13chSsEG61bC26sC/tbrXAF6L7R5lDLYgeo2Iy0ertZaE+Pt2amotnE0pcI=
    on:
      tags: true
      repo: bealearts/qlik-sense-webpack-plugin
  - provider: releases
    api_key:
      secure: oxOazztBffPekKiZUmy9sDfzzBIw+m0DW3AgiDd0SyRkqts6CSee5cJb6N4eoDlQbiPPQS6v9VNVlkiZ2HM3EEWeUuY7uNH9/WXwxi0kJli5CUeGfIAUsKOXjUPu0qW0y+fH1Lv+FfbUcUdN52v8BNWY8pLXad7ZUW9lAoHEuboRk16C7WfX31K8PzfOb9RM53Ge+FXSwUI9wmrdvszPqNS3v7a0T2DogjvrUeASvYDSSjh2biiEox84DX/YNG4sS8Z5De8czV1FQbVLTyd1m8YcKNYT/k1cCRSaOG7rQY/UZGEFrHuSf6ZQPpc+ENqIMecKO7T5KwuGSM0hRUR5McKPGeVTyn1xq6Gw13GD+ekVCjWamt8LePhFJb3+6hZEUHApd1izCJiS9l0LmDzrqe9v7X2yNR46F2UR0QIbRsn1w/XxGZrR6Tk2mlhMHaeZBwFI8sP0hbOIfAp7jlYN3m+7qvrGqLUJpr/Zo9saPpCQJ5CBvsAYex/ij1AyUKGCpU/BBHUQsoDOn8gAPp8i9b3/CNy3Iakp06/tqXshQAStIoEbo9IfkFg3vTTclkr4sLy9zqYexcbvB8rmHmB0+bTfuX8PwcVJMRWVmI5UpTRPHVfiyWR5f4M94OD1WHPk7pLDFrol85UMQutsE08bB+0e2zT1eeFwdLAkcRy8Ysw=
    file: ''
    on:
      tags: true
      repo: bealearts/qlik-sense-webpack-plugin
