language: node_js
node_js:
- 6.9.2
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: MsIxauc8Aw8QmJ6tnE4D2okY/dwiE822ezvtJf3eDJf0vjfUo+y7rn+5am8v/xEl/zDLInBm9IwBobjdKarK6l7ptjtf9S99RwiEwa2oYnrOa39yZ9eVY/Gn5KtGcNuI13Yb0uJ0kEPGiK9l0Q9CGKpVF1LfmFDCslr0Xa8JFaZz6ypP+MIA1K30JKFtVaxIhOvo+1DCbIO9ZFHXoefolfE2ZhsGX53TQG4A5Twjs1x24wcVxnkzrHzLYuCGTcpVv4tnJuckq6sp1p4CaBTEVaolJYslZWU0Ewc1U/ClW5CKpuxpjiJqT4tQmjNpLQTPu+SqmuG0QoN7Fy72k4ZHmhHlsb2yUrBSf4Zt0AlE4CIYrhxlush0nB6OWG9dHuExuo15i6ALBmehNz0tVWLpMGfDkKB3pnicyTRjVrerZFl+O5vR9BJqqz9wVOx2mEq5POljlTIoBrJaAYCxnjg0O9HbWK2Tdb2jayCOAng18g9ii9I7X2ewAddOTCg/uYgBU0iQXtq95a+CBiEEZ11Jd9CHTETIXmfWgorBC31ZnqXeTfdgIGQVrbG/YMMBeop8IdS9+L98BAmKyX8WPEnTotsh3i3ZqSHf6geBzGSb8rtCRexq13chSsEG61bC26sC/tbrXAF6L7R5lDLYgeo2Iy0ertZaE+Pt2amotnE0pcI=
  on:
    tags: true
    repo: bealearts/qlik-sense-webpack-plugin
